import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";  // Assurez-vous que le fichier globals.css est dans le bon dossier

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Application manager organisation Sms",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="description" content="Speed up your development with a complete and scalable gulpjs based build system that scaffolds the project for you." />
        <meta name="copyright" content="Copyright Gulp Tailwind Starter 2023. All Rights Reserved." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
